config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  
  get 'users/:id/child', to: 'children#new', as: :child_new
  post 'users/:id/child', to: 'children#create'
  
  get 'users/:id/messages', to: 'messages#index', as: :messages
  get 'users/:id/message', to: 'messages#new', as: :message_new
  post 'users/:id/message', to: 'messages#create'
  delete '/messages/:id(.:format)', to: 'messages#destroy', as: :message
  
  get 'posts/search', to: 'posts#search'
  get 'posts/new_search', to: 'posts#new_search'
  
  resources :posts, only: [:index, :show, :new, :create, :delete]
  
  post 'posts/:id', to: 'responses#create', as: :responses_new
  delete 'posts/:id', to: 'responses#destroy', as: :responses
  

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :gender, presence: true, inclusion: { in: ['男性', '女性'] }
  validates :birth, presence: true
  validate :birth_future_date?
  has_secure_password
  
  has_many :children, dependent: :destroy
  accepts_nested_attributes_for :children, allow_destroy: true
  
  validates :children, presence: true
  validates_associated :children
  
  has_many :messages
  has_many :posts
  has_many :responses
  
  private
  
  def birth_future_date?
    # 生年月日が入力済かつ未来日(現在日付より未来)
    if birth.present? && birth > Date.today
      # エラー対象とするプロパティ(birthday)とエラーメッセージを設定
      errors.add(:birth, "生年月日に未来日は指定できません")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  def show
    @user = User.find(params[:id])
    @pagy, @children = pagy(@user.children.order(child_birth: :asc), items: 3)
  
  end

  def new
    @user = User.new
    @children = @user.children.build
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :birth, :gender, :password, :password_confirmation, children_attributes: [:child_gender, :child_birth, :destroy, :id])
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/new.html.erb
<div class="text-center">
  <h2>ユーザー登録</h2>
</div>

<div class="row justify-content-center">
  <div class="col-sm-6">

    <%= form_with(model: @user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="m-3">
        <%= f.text_field :name, placeholder: 'ユーザ名', class: 'form-control' %>
      </div>
      <div class="m-3">
        <%= f.email_field :email, placeholder: 'メールアドレス', class: 'form-control' %>
      </div>
      <div class="row m-3 py-2 border rounded">
          <div class="col-sm-4 m-1">
            性別
          </div>
          <div style="text-align: center">
            <%= f.radio_button :gender, :男性 %>
            <%= f.label :gender, "男性", {value: :男性, style: "display: inline-block;"} %>
            <%= f.radio_button :gender, :女性 %>
            <%= f.label :gender, "女性", {value: :女性, style: "display: inline-block;"} %>
          </div>
      </div>
      <div class="row m-3 py-2 border rounded">
        <div class="col-sm-4 m-1">
          生年月日
        </div>
        <div>
          <%= f.date_field :birth, class: 'form-control' %>
        </div>
      </div>
      <%= f.fields_for :children do |c| %>
        <div class="row m-3 py-2 border rounded">
          <div class="col-sm-6 m-1">
            お子様性別
          </div>
          <div class="col-sm-16" style="text-align: center">
            <%= c.radio_button :child_gender, :男性 %>
            <%= c.label :child_gender, "男性", {value: :男性, style: "display: inline-block;"} %>
            <%= c.radio_button :child_gender, :女性 %>
            <%= c.label :child_gender, "女性", {value: :女性, style: "display: inline-block;"} %>
          </div>
        </div>
        <div class="row m-3 p-2 border rounded">
          <div class="col-sm-8 m-1 px-0">
            お子様の生年月日または出産予定日      
          </div>
          <div class="sm-16">
            <%= c.date_field :child_birth, class: 'form-control' %>
          </div>
        </div>
      <% end%>
      
      <div class="m-3">
        <%= f.password_field :password, placeholder: 'パスワード', class: 'form-control' %>
      </div>
      
      <div class="m-3">
        <%= f.password_field :password_confirmation, placeholder: 'パスワード再入力', class: 'form-control' %>
      </div>
      
      <div class="m-3">
        <%= f.submit 'ユーザー登録', class: 'btn btn-secondary w-100' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h2 class=pb-3>ユーザー情報</h2>

<div class="row justify-content-center">
  <div class="col-sm-6 offset-sm-4 px-4">
    <img class="rounded-circle me-2 mt-1" src="<%= gravatar_url(@user, { size: 64 }) %>" alt="">
  </div>
  <div class="col-sm-6 offset-sm-3">
    <div class="form-group row">
      <div class="col-sm-6">
        <label class="col-form-label">ユーザー名
          <input class="form-control m-1" type="text" placeholder=<%= @user.name %> readonly>
        </label>
        <label class="col-form-label">性別
          <input class="form-control m-1" type="text" placeholder=<%= @user.gender %> readonly>
        </label>
        <label class="col-form-label">生年月日
          <input class="form-control m-1" type="text" placeholder=<%= @user.birth %> readonly>
        </label>
      </div>
        <% @children.each_with_index do |c, i| %>
          <% j = @pagy.page %>
          <% num = 3* (j-1) + (i+1) %>
          <div class="form-group row">
            <div class="col-sm-8">
              <label class="col-form-label"><%= "お子様性別(第#{num}子)" %>
                <input class="form-control m-1" type="text" placeholder=<%= c.child_gender %> readonly>
              </label>
              <label class="col-form-label"><%= "お子様生年月日(第#{num}子)"%>
                <input class="form-control m-1" type="text" placeholder=<%= c.child_birth %> readonly>
              </label>
            </div>
          </div>
        <% end %>
    </div>

    <div class="mt-2 mb-2">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
    
    <%= link_to child_new_url(current_user.id) do %>
      <i class="m-3 btn btn-secondary w-200">お子様情報追加</i>
    <% end %>
  </div>
</div>