config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  
  get 'users/:id/child', to: 'children#new', as: :child_new
  post 'users/:id/child', to: 'children#create'
  
  get 'users/:id/messages', to: 'messages#index', as: :messages
  get 'users/:id/message', to: 'messages#new', as: :message_new
  post 'users/:id/message', to: 'messages#create'
  delete '/messages/:id(.:format)', to: 'messages#destroy', as: :message
  
  get 'posts/search', to: 'posts#search'
  get 'posts/new_search', to: 'posts#new_search'
  
  resources :posts, only: [:index, :show, :new, :create, :delete]
  
  post 'posts/:id', to: 'responses#create', as: :responses_new
  delete 'posts/:id', to: 'responses#destroy', as: :responses
  

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
  end

  def create
    @response = Response.new(response_params)

    if @response.save
      flash[:success] = '回答を送信しました。'
      redirect_to :post
    else
      flash[:danger] = '回答の送信に失敗しました。'
      redirect_to :post, flash: { error: @response.errors.full_messages }
    end
  end

  def destroy
    @response = Response.find(params[:response_id])
    @response.destroy
    flash[:success] = '回答を削除しました'
    redirect_back(fallback_location: @post)
  end
  
  
  private
  
  def response_params
    params.require(:response).permit(:user_id, :post_id, :content, :image)
  end
end

app/views/responses/_responses.html.erb
<% if logged_in? %>
  <% @responses.each do |response| %>
    <div class="row p-1 m-1">
      <div class="col-sm-2 text-center mt-4">
        <img class="rounded-circle me-2 mt-1" src="<%= gravatar_url(response.user, { size: 60 }) %>" alt=""><br>
        <% if current_user == response.user %>
          <strong class="mx-2"><%= response.user.name %></strong>
        <% else %>
          <%= link_to response.user.name, message_new_path(id: current_user.id, chat_user_id: response.user.id) %>
        <% end %>
      </div>
      <div class="col-sm-9 mt-4 h-auto border rounded p-2" style="background-color: #F5FFFA;" >
        <%= simple_format(response.content) %>
        <% if response.image? %>
          <%= image_tag response.image.url, :alt => 'image' %>
        <% end %>
      </div>
      <% if current_user.name == response.user.name %>
      <div class="col-sm-1 text-center mt-4 pt-4">
        <%= link_to "削除", responses_url(response_id: response.id), method: :delete, data: { confirm: "回答を削除しますか?" }, class: 'btn btn-danger btn-sm' %>
      </div>
      <% end %>
    </div>
    <div class="offset-sm-2 px-1 py-0">
      <% response_time = response.created_at + ( 9 * 60 * 60 ) %>
      <p class= "text-gray-dark"><%= response_time.strftime("%Y年%m月%d日%H:%M")%></p>
    </div>
  <% end %>
    <div class="row" style="align-items: flex-end;">
    <aside class="offset-sm-2 col-sm-9" >
      <% if flash[:error].present? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% flash[:error].each do |e| %>
              <li><%= e %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with(model: @response, url: responses_new_path) do |f| %>
        <div class="mb-3">
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :post_id, :value => @post.id %>
          <%= f.text_area :content, placeholder: '回答内容', class: 'form-control', rows: 5 %>
        </div>
        <div class="col-sm-12 d-flex" style="justify-content: flex-end;">
          <%= f.file_field :image %>
          <%= button_tag( class: "btn btn-default btn-sm") do %>
            <i class="far fa-paper-plane fa-3x"></i>
          <% end %>
        </div> 
      <% end %>
    </aside>
    </div>
  <% else %>
    <% @responses.each do |response| %>
      <div class="row p-1 m-1">
        <div class="col-sm-1 text-center mt-4">
          <img class="rounded-circle me-2 mt-1" src="<%= gravatar_url(response.user, { size: 60 }) %>" alt=""><br>
            <strong class="mx-2"><%= response.user.name %></strong>
        </div>
        <div class="col-sm-11 mt-4 h-auto border rounded p-2" style="background-color: #F5FFFA;" >
          <%= simple_format(response.content) %>
          <% if response.image? %>
            <%= image_tag response.image.url, :alt => 'image' %>
          <% end %>
        </div>
      </div>
      <div class="offset-sm-1 px-1 py-0">
        <% response_time = response.created_at + ( 9 * 60 * 60 ) %>
        <p class= "text-gray-dark"><%= response_time.strftime("%Y年%m月%d日%H:%M")%></p>
      </div>
    <% end %>
    <div class="offset-sm-1">
      <%= link_to 'ログインし、回答を送信する', login_path %>
    </div>
  <% end %>