config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  
  get 'users/:id/child', to: 'children#new', as: :child_new
  post 'users/:id/child', to: 'children#create'
  
  get 'users/:id/messages', to: 'messages#index', as: :messages
  get 'users/:id/message', to: 'messages#new', as: :message_new
  post 'users/:id/message', to: 'messages#create'
  delete '/messages/:id(.:format)', to: 'messages#destroy', as: :message
  
  get 'posts/search', to: 'posts#search'
  get 'posts/new_search', to: 'posts#new_search'
  
  resources :posts, only: [:index, :show, :new, :create, :delete]
  
  post 'posts/:id', to: 'responses#create', as: :responses_new
  delete 'posts/:id', to: 'responses#destroy', as: :responses
  

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  
  has_many :responses, dependent: :destroy
  validates :user, presence: true
  validates :category, presence: true
  validates :title, presence: true, length: { maximum: 15 }
  validates :content, presence: true, unless: :image?, length: { maximum: 500 }
  mount_uploader :image, ImageUploader
  
  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'category'
      return all.includes(:category).order("categories.name desc")
    end
  end
  

  def self.search(search_keyword)
    where(["title like? OR name like?", "%#{search_keyword}%", "%#{search_keyword}%"])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    selection = params[:keyword] || "new"
    search_keyword = params[:search_keyword]
    if search_keyword.present?
       @posts = Post.includes(:category).references(:category).search(search_keyword)

      if selection == "new"
        @pagy, @posts = pagy_array(@posts.sort{|a, b| b[:created_at] <=> a[:created_at]})
      elsif selection == "old"
        @pagy, @posts = pagy_array(@posts.sort{|a, b| a[:created_at] <=> b[:created_at]})
      elsif selection == "category"
        @pagy, @posts = pagy_array(@posts.sort{|a, b| a[:category_name] <=> b[:category_name]})
      end
      
    else
      @pagy, @posts = pagy(Post.sort(selection))
    end
  end

  def show
    @post = Post.find(params[:id])
    @responses = @post.responses.includes([:user, :post]).order(created_at: :desc)
    @response = Response.new
  end

  def new
    @categories = Category.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:success] = 'お悩みを投稿しました。'
      redirect_to :root
    else
      flash[:danger] = 'お悩み投稿に失敗しました。'
      redirect_to :new_post, flash: { error: @post.errors.full_messages }
    end
  end

  def destroy
  end

  def new_search
    @categories = Category.all
  end
  
  def search
    @pagy, @posts = pagy(Post.includes(:category).references(:category).search(params[:search_keyword]))
    @search_keyword = params[:search_keyword]
    redirect_to root_path(search_keyword: @search_keyword)
  end
  
  private
  
  def post_params
    params.require(:post).permit(:user_id, :category_id, :title, :content, :image)
  end
  
end

app/views/posts/_posts.html.erb
<ul class="list-unstyled mt-2">
  <% if logged_in? %>
    <% posts.each do |post| %>
      <li class="d-flex border rounded mb-2">
        <div class="col-sm-1 mt-2 text-center">
          <% if current_user == post.user %>
            <p class="m-1">
              <img class="rounded-circle p-1 mt-1" src="<%= gravatar_url(post.user, { size: 42 }) %>" alt=""><br>
              <strong class="mx-2"><%= post.user.name %></strong>
            </p>
          <% else %>
            <p class="m-1">
              <img class="rounded-circle p-1 mt-1" src="<%= gravatar_url(post.user, { size: 42 }) %>" alt=""><br>
              <strong class="mx-2"><%= link_to post.user.name, message_new_path(id: current_user.id, chat_user_id: post.user.id) %></strong>
            </p>
          <% end %>
        </div>
        <div class="m-3">
          <p class="my-1"><%= post.category.name %></p>
          <p class="my-1"><strong><%= link_to post.title, post_url(post) %></strong></p>
          <% message_time = post.created_at + ( 9 * 60 * 60 ) %>
          <p class= "text-gray-dark"><%= message_time.strftime("%Y年%m月%d日%H:%M")%></p>
        </div>
      </li>
    <% end %>
  <% else %>
    <% posts.each do |post| %>
      <li class="d-flex border rounded mb-2">
        <div class="col-sm-1 mt-2 text-center">
          <p class="m-1">
            <img class="rounded-circle p-1 mt-1" src="<%= gravatar_url(post.user, { size: 42 }) %>" alt=""><br>
            <strong><%= post.user.name %></strong>
          </p>
        </div>
        <div class="m-2">
          <p class="my-1"><%= post.category.name %></p>
          <p class="my-1"><strong><%= link_to post.title, post_url(post) %></strong></p>
          <% message_time = post.created_at + ( 9 * 60 * 60 ) %>
          <p class= "text-gray-dark"><%= message_time.strftime("%Y年%m月%d日%H:%M")%></p>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/posts/index.html.erb
<h2 style="display: inline">お悩み一覧</h2>
<div class="btn-group offset-sm-9">
  <%= link_to posts_new_search_url do %>
    <i class="m-3 btn btn-secondary w-200">お悩み検索</i>
  <% end %>
  <%= link_to new_post_url do %>
    <i class="m-3 btn btn-secondary w-200">お悩み投稿</i>
  <% end %>
</div>
<div class="mb-3">
  <%= form_with model: @post, url: posts_path, method: :get, local: true do |f| %>
    <%= f.hidden_field :search_keyword, :value => params[:search_keyword] %>
    <%= f.select :keyword, {'投稿が新しい順': 'new', '投稿が古い順': 'old', 'カテゴリ順': 'category'}, {selected: params[:keyword]} %>
    <%= f.submit '並べ替え'%>
  <% end %>
</div>
<div class=row>
  <div class="col-sm-12 border rounded p-2">
    <%= render 'posts/posts', posts: @posts %>
  </div>
</div>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/posts/new.html.erb
<h2>お悩み投稿</h2>
<% if flash[:error].present? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% flash[:error].each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if logged_in? %>
  <%= form_with(model: @post, url: posts_path) do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="row justify-content-center">
    <div class="col-sm-11 my-3">
      <%= f.text_field :title, placeholder: "タイトル", class: 'form-control' %>
    </div>
    <div class="col-sm-11 my-3">
      <%= f.text_area :content, placeholder: "お悩み内容", class: 'form-control', rows: 5 %>
    </div>
    <div class="col-sm-11 my-3">
      <%= f.select :category_id, @categories.map{ |category| [category.name, category.id]}, { include_blank: 'カテゴリー選択'}, { class: 'form-control' , required: true }%>
    </div>
    <div class="col-sm-11 d-flex" style="justify-content: space-between;">
      <%= f.file_field :image %>
      
      <%= button_tag( class: "btn btn-default btn-sm") do %>
        <i class="far fa-paper-plane fa-3x"></i>
      <% end %>
    </div>
  </div>
  <% end %>
<% else %>
  <%= link_to 'ログインし、お悩みを登録する', login_path %>
<% end %>

app/views/posts/new_search.html.erb
<h2 style="display: inline">お悩み検索</h2>

<%= form_with url: posts_search_url, method: :get, local: true, id: "form4" do |f| %>
  <div class="row my-4">
    <div class="col-sm-4">
      <%= f.text_field :search_keyword, placeholder: "タイトルまたはカテゴリーにて検索", value: @keyword, id: "sbox4", class: 'form-control' %>
    </div>
    <div class="col-sm-2 ">
      <%= button_tag( class: "btn btn-default btn-sm", id: "sbtn4") do %>
        <i class="fa fa-search fa-2x"></i>
      <% end %>
    </div>
  </div>
<% end %>

<h4 style="display: inline">カテゴリー一覧</h4>
<div class="post-list">
  <ul>
    <% @categories.each do |category| %>
      <li><%= category.name %></li>
    <% end %>
  </ul>
</div>

app/views/posts/show.html.erb
<h2>お悩み</h2>
<div class="row p-1 m-1 ">
  <div class="col-sm-2 text-center mt-4">
    <p class="m-1 text-center">
      <img class="rounded-circle" src="<%= gravatar_url(@post.user, { size: 60 }) %>" alt=""><br>
      <strong class="mx-2"><%= @post.user.name %></strong>
    </p>
  </div>
  <div class="col-sm-9 h-auto">
    <strong style="font-size:18px;"><%= @post.title %></strong>
    <div class="d-flex-column border rounded p-2" style="background-color: #FFFAF0;">
      <%= simple_format(h(@post.content))%>
      <% if @post.image? %>
        <%= image_tag @post.image.url , :alt => 'image' %>
      <% end %>
    </div>
      <% message_time = @post.created_at + ( 9 * 60 * 60 ) %>
      <p class= "text-gray-dark"><%= message_time.strftime("%Y年%m月%d日%H:%M")%></p>
  </div>
</div>

<h2>回答</h2>
<%= render 'responses/responses', responses: @responses %>



  

  