config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  
  get 'users/:id/child', to: 'children#new', as: :child_new
  post 'users/:id/child', to: 'children#create'
  
  get 'users/:id/messages', to: 'messages#index', as: :messages
  get 'users/:id/message', to: 'messages#new', as: :message_new
  post 'users/:id/message', to: 'messages#create'
  delete '/messages/:id(.:format)', to: 'messages#destroy', as: :message
  
  get 'posts/search', to: 'posts#search'
  get 'posts/new_search', to: 'posts#new_search'
  
  resources :posts, only: [:index, :show, :new, :create, :delete]
  
  post 'posts/:id', to: 'responses#create', as: :responses_new
  delete 'posts/:id', to: 'responses#destroy', as: :responses
  

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% unless message_type == 'error' %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #0fc47a;">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">子育て助け合い広場</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% if logged_in? %>
        <div class="btn-group">
          <ul class="navbar-nav">
            <li class="ms-3"><%= link_to 'ユーザー情報', user_path(current_user), class: 'nav-link' %></li>
            <li class="ms-3"><%= link_to 'メッセージ', messages_path(current_user), class: 'nav-link' %></li>
            <li class="ms-3"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
          </ul>
        </div>
      <% else %>
          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item"><%= link_to 'ユーザー登録', signup_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
            </ul>
          </div>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Childcare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="./stylesheets/application.css">  
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  
  <body data-turbolinks="false">
    <div class="wrapper">
      <%= render 'layouts/navbar' %>
    
      <div class="container">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    
      <footer>
        COPYRIGHT (C) 2021 子育て助け合い広場​. ALL RIG​HTS RESERVED.
      </footer>
    
    </div>
  </body>
    



</html>